# Generated by Django 3.0.5 on 2020-04-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('message', models.CharField(max_length=600)),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
