# Generated by Django 3.0.5 on 2020-04-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='message',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
